name: publish

on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - name: Login to GitHub Container Registry
#      uses: docker/login-action@v1
#      with:
#        registry: ghcr.io
#        username: Darkside138
#        password: ${{ secrets.SOUNDBOARD_GHCR }}
#        repository: Darkside138/DiscordSoundboard
#        dockerfile: Dockerfile

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: Darkside138
        password: ${{ secrets.SOUNDBOARD_GHCR }}
        registry: ghcr.io
        repository: darkside138/discordsoundboard
        tags: ${{ github.sha }}
        dockerfile: Dockerfile

#    - name: Build the Discord Soundboard Docker image
#      run: |
#        docker build . --tag ghcr.io/darkside138/discord-soundboard:latest
#        docker run ghcr.io/darkside138/discord-soundboard:latest
#        docker push ghcr.io/darkside138/discord-soundboard:latest
