name: publish

on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: Darkside138
        password: ${{ secrets.SOUNDBOARD_GHCR }}
        
    - name: Build the Discord Soundboard Docker image
      run: |
        docker build . --tag ghcr.io/darkside138/discord-soundboard:latest
        docker run ghcr.io/darkside138/discord-soundboard:latest
        docker push ghcr.io/darkside138/discord-soundboard:latest
